// Banco de dados local de produtos - Clarim Perfumes
const produtos = [
    {
        id: 1,
        nome: "Affection",
        marca: "Lattafa Pride",
        categoria: "Compartilhável",
        tipo: "Árabe",
        preco: 360.00,
        descricao: "Affection (Lattafa Pride) é um perfume cremoso e gourmand. As notas de topo são Pistache, Avelã e Cassis; as notas de coração são Jasmim, Lírio-do-Vale e Lactonas; as notas de fundo são Baunilha, Fava Tonka e Sândalo.",
        imagem: "assets/perfumes/Affection.webp",
        destaque: true
    },
    {
        id: 2,
        nome: "Al Batal",
        marca: "Lattafa Perfumes",
        categoria: "Masculino",
        tipo: "Árabe",
        preco: 290.00,
        descricao: "Al Batal de Lattafa Perfumes é um perfume oriental amadeirado e marcante. Apresenta notas de topo cítricas e especiadas, um coração floral e resinoso, e notas de fundo de Âmbar, Almíscar e Notas Amadeiradas.",
        imagem: "assets/perfumes/Al Batal.webp",
        destaque: false
    },
    {
        id: 3,
        nome: "Al Noble Ameer",
        marca: "Lattafa Perfumes",
        categoria: "Compartilhável",
        tipo: "Árabe",
        preco: 320.00,
        descricao: "Al Noble Ameer de Lattafa Perfumes é um perfume amadeirado especiado lançado em 2022. As notas de topo são Maçã, Pimenta Rosa e Bergamota; as notas de coração são Cravo-da-Índia e Cipriol; as notas de fundo são Madeira de Oud, Vetiver, Âmbar e Patchouli.",
        imagem: "assets/perfumes/Al Noble Ameer.webp",
        destaque: false
    },
    {
        id: 4,
        nome: "Al Noble Safeer",
        marca: "Lattafa Perfumes",
        categoria: "Compartilhável",
        tipo: "Árabe",
        preco: 320.00,
        descricao: "Al Noble Safeer de Lattafa Perfumes é um perfume aromático verde lançado em 2022. As notas de topo são Sálvia e Bergamota; as notas de coração são Notas Verdes e Especiarias; as notas de fundo são Madeira de Guaiaco, Musgo de Carvalho e Patchouli.",
        imagem: "assets/perfumes/Al Noble Safeer.webp",
        destaque: false
    },
    {
        id: 5,
        nome: "Al Noble Wazeer",
        marca: "Lattafa Perfumes",
        categoria: "Compartilhável",
        tipo: "Árabe",
        preco: 320.00,
        descricao: "Al Noble Wazeer de Lattafa Perfumes é um perfume amadeirado frutado lançado em 2022. As notas de topo são Hortelã, Laranja Amarga, Bergamota e Juniper; as notas de coração são Íris, Chocolate, Framboesa e Caramelo; as notas de fundo são Baunilha, Âmbar, Madeira de Guaiaco e Cedro.",
        imagem: "assets/perfumes/Al Noble Wazeer.webp",
        destaque: false
    },
    {
        id: 6,
        nome: "Ameerat Al Arab Prive Rose",
        marca: "Asdaaf",
        categoria: "Feminino",
        tipo: "Árabe",
        preco: 320.00,
        descricao: "Ameerat Al Arab Prive Rose de Asdaaf é um perfume floral frutado lançado em 2023. As notas de topo são Morango, Uva e Laranja; as notas de coração são Rosa, Jasmim, Gardenia e Ylang-Ylang; as notas de fundo são Fava Tonka, Âmbar e Sândalo.",
        imagem: "assets/perfumes/Ameerat Al Arab Prive Rose.webp",
        destaque: false
    },
    {
        id: 7,
        nome: "Ameerat Al Arab",
        marca: "Asdaaf",
        categoria: "Feminino",
        tipo: "Árabe",
        preco: 280.00,
        descricao: "Ameerat Al Arab de Asdaaf é um perfume floral compartillhado refinado. As notas de topo são Cítricos e Aloe Vera; as notas de coração são Jasmim e Almíscar; as notas de fundo são Notas Amadeiradas, Âmbar e Almíscar.",
        imagem: "assets/perfumes/Ameerat Al Arab.webp",
        destaque: false
    },
    {
        id: 8,
        nome: "Armaf Club De Nuit Intense Man",
        marca: "Armaf",
        categoria: "Masculino",
        tipo: "Árabe",
        preco: 420.00,
        descricao: "Club de Nuit Intense Man de Armaf é um perfume Amadeirado Especiado lançado em 2015. As notas de topo são Limão, Abacaxi, Bergamota, Groselha Preta e Maçã; as notas de coração são Bétula, Jasmim e Rosa; as notas de fundo são Almíscar Cinzento, Âmbar Cinzento, Patchouli e Baunilha.",
        imagem: "assets/perfumes/Armaf Club De Nuit Intense Man.webp",
        destaque: true
    },
    {
        id: 9,
        nome: "Asad Bourbon",
        marca: "Lattafa Perfumes",
        categoria: "Masculino",
        tipo: "Árabe",
        preco: 350.00,
        descricao: "Asad Bourbon de Lattafa Perfumes é uma variação rica e licorosa da linha Asad. Apresenta notas de topo de Pimenta Preta, Lavanda e Cacau; notas de coração de Licor de Bourbon e Íris; e notas de fundo de Baunilha Bourbon, Âmbar e Cedro.",
        imagem: "assets/perfumes/Asad Bourbon.webp",
        destaque: false
    },
    {
        id: 10,
        nome: "Asad Elixir",
        marca: "Lattafa Perfumes",
        categoria: "Masculino",
        tipo: "Árabe",
        preco: 390.00,
        descricao: "Asad Elixir de Lattafa Perfumes é uma versão mais intensa e concentrada do clássico Asad. Possui notas de topo de Pimenta Preta, Abacaxi e Tabaco; notas de coração de Café, Patchouli e Íris; e notas de fundo de Âmbar, Baunilha, Benjoin e Madeiras Nobres.",
        imagem: "assets/perfumes/Asad Elixir.webp",
        destaque: false
    },
    {
        id: 11,
        nome: "Asad Zanzibar",
        marca: "Lattafa Perfumes",
        categoria: "Masculino",
        tipo: "Árabe",
        preco: 330.00,
        descricao: "Asad Zanzibar de Lattafa Perfumes é um perfume aromático e especiado lançado em 2024. As notas de topo são Pimenta Preta e Lavanda; as notas de coração são Água de Coco, Iris e Sal; as notas de fundo são Baunilha e Incenso.",
        imagem: "assets/perfumes/Asad Zanzibar.webp",
        destaque: false
    },
    {
        id: 12,
        nome: "Atheeri",
        marca: "Asdaaf",
        categoria: "Feminino",
        tipo: "Árabe",
        preco: 270.00,
        descricao: "Atheeri de Lattafa / Asdaaf é uma fragrância floral oriental elegante. As notas de topo são Cítricos e Pimenta Rosa; as notas de coração são Rosa, Jasmim e Flor de Laranjeira; as notas de fundo são Baunilha, Âmbar e Almíscar.",
        imagem: "assets/perfumes/Atheeri.webp",
        destaque: false
    },
    {
        id: 13,
        nome: "Bad Femme",
        marca: "Maison Alhambra",
        categoria: "Feminino",
        tipo: "Árabe",
        preco: 260.00,
        descricao: "Bad Femme de Maison Alhambra é um perfume oriental floral marcante e ousado. Apresenta notas de topo de Amêndoa e Café; notas de coração de Tuberosa e Jasmim Sambac; e notas de fundo de Fava Tonka, Cacau e Baunilha.",
        imagem: "assets/perfumes/Bad Femme.webp",
        destaque: false
    },
    {
        id: 14,
        nome: "Bonbon-Armaf",
        marca: "Armaf",
        categoria: "Feminino",
        tipo: "Árabe",
        preco: 290.00,
        descricao: "Bonbon da Armaf é uma fragrância doce e envolvente. As notas de topo são Frutas Cítricas e Bagas Doces; as notas de coração são Caramelo, Flor de Laranjeira e Jasmim; as notas de fundo são Baunilha, Âmbar e Almíscar.",
        imagem: "assets/perfumes/Bonbon-Armaf.webp",
        destaque: false
    },
    {
        id: 15,
        nome: "Cleopatra",
        marca: "Tocca",
        categoria: "Feminino",
        tipo: "Importado",
        preco: 850.00,
        descricao: "Cleopatra de Tocca é um perfume Âmbar Floral Feminino lançado em 2007. As notas de topo são Toranja, Notas Verdes, Cassis e Cassia; as notas de coração são Jasmim, Íris e Tuberosa; as notas de fundo são Almíscar, Âmbar, Patchouli e Baunilha.",
        imagem: "assets/perfumes/Cleopatra.webp",
        destaque: false
    },
    {
        id: 16,
        nome: "Club De Nuit Bling",
        marca: "Armaf",
        categoria: "Feminino",
        tipo: "Árabe",
        preco: 380.00,
        descricao: "Club De Nuit Woman Bling Edition de Armaf é um perfume Floral Frutado. As notas de topo são Laranja, Bergamota, Toranja e Pêssego; as notas de coração são Rosa, Jasmim, Litchi e Gerânio; as notas de fundo são Patchouli, Baunilha, Vetiver e Almíscar.",
        imagem: "assets/perfumes/Club De Nuit Bling.webp",
        destaque: false
    },
    {
        id: 17,
        nome: "Club De Nuit Iconic",
        marca: "Armaf",
        categoria: "Masculino",
        tipo: "Árabe",
        preco: 480.00,
        descricao: "Club de Nuit Blue Iconic de Armaf é um perfume Âmbar Amadeirado lançado em 2022. As notas de topo são Toranja, Limão, Hortelã, Pimenta Rosa e Bergamota; as notas de coração são Gengibe, Nutmeg e Jasmim; as notas de fundo são Incenso, Âmbar, Cedro, Sândalo e Patchouli.",
        imagem: "assets/perfumes/Club De Nuit Iconic.webp",
        destaque: false
    },
    {
        id: 18,
        nome: "Club De Nuit Intense (Feminino)",
        marca: "Armaf",
        categoria: "Feminino",
        tipo: "Árabe",
        preco: 390.00,
        descricao: "Club de Nuit Intense Woman de Armaf é um perfume Chypre Floral lançado em 2013. As notas de topo são Rosa, Açafrão e Gerânio; as notas de coração são Noz-moscada, Pimenta, Violeta e Alcaravia; as notas de fundo são Patchouli, Baunilha, Âmbar e Oud.",
        imagem: "assets/perfumes/Club De Nuit Intense.webp",
        destaque: false
    },
    {
        id: 19,
        nome: "Club De Nuit Maleka",
        marca: "Armaf",
        categoria: "Feminino",
        tipo: "Árabe",
        preco: 410.00,
        descricao: "Club de Nuit Maleka de Armaf é uma fragrância majestosa e sofisticada. As notas de topo são Açafrão, Frutas Silvestres e Bergamota; as notas de coração são Rosa, Âmbar e Jasmim; as notas de fundo são Oud, Baunilha e Sândalo.",
        imagem: "assets/perfumes/Club De Nuit Maleka.webp",
        destaque: false
    },
    {
        id: 20,
        nome: "Club De Nuit Man",
        marca: "Armaf",
        categoria: "Masculino",
        tipo: "Árabe",
        preco: 320.00,
        descricao: "Club de Nuit Man de Armaf é um perfume Especiado Amadeirado. As notas de topo são Tangerina, Hortelã e Toranja; as notas de coração são Canela, Gengibre, Pimenta e Cravo; as notas de fundo são Âmbar, Couro, Notas Amadeiradas e Patchouli.",
        imagem: "assets/perfumes/Club De Nuit Man.webp",
        destaque: false
    },
    {
        id: 21,
        nome: "Club De Nuit Milestone",
        marca: "Armaf",
        categoria: "Compartilhável",
        tipo: "Árabe",
        preco: 450.00,
        descricao: "Club de Nuit Milestone de Armaf é um perfume Amadeirado Floral Almiscarado lançado em 2019. As notas de topo são Notas Marinhas, Frutas e Sal Marinho; as notas de coração são Limão Siciliano, Bergamota, Íris e Tangerina; as notas de fundo são Almíscar e Notas Amadeiradas.",
        imagem: "assets/perfumes/Club De Nuit Milestone.webp",
        destaque: false
    },
    {
        id: 22,
        nome: "Club De Nuit Untold",
        marca: "Armaf",
        categoria: "Compartilhável",
        tipo: "Árabe",
        preco: 490.00,
        descricao: "Club de Nuit Untold de Armaf é um perfume Âmbar Amadeirado lançado em 2022. As notas de topo são Açafrão e Jasmim; as notas de coração são Madeira de Âmbar e Âmbar Cinzento; as notas de fundo são Resina de Abeto e Cedro.",
        imagem: "assets/perfumes/Club de Nuit Untold.webp",
        destaque: false
    },
    {
        id: 23,
        nome: "Club De Nuit Urban",
        marca: "Armaf",
        categoria: "Masculino",
        tipo: "Árabe",
        preco: 380.00,
        descricao: "Club de Nuit Urban Man de Armaf é um perfume Amadeirado Especiado lançado em 2017. As notas de topo são Toranja, Bergamota, Hortelã e Cardamomo; as notas de coração são Gengibre, Noz-moscada, Cedro e Lavanda; as notas de fundo são Vetiver, Sândalo, Patchouli e Musgo de Carvalho.",
        imagem: "assets/perfumes/Club de Nuit Urban.webp",
        destaque: false
    },
    {
        id: 24,
        nome: "Delilah-blanc",
        marca: "Maison Alhambra",
        categoria: "Feminino",
        tipo: "Árabe",
        preco: 280.00,
        descricao: "Delilah Blanc de Maison Alhambra é uma fragrância floral branca fresca e delicada. As notas de topo são Litchi, Bergamota e Peônia Branca; as notas de coração são Rosa Branca, Jasmim e Lírio-do-Vale; as notas de fundo são Almíscar Branco, Âmbar e Madeira de Cedro.",
        imagem: "assets/perfumes/Delilah-blanc.webp",
        destaque: false
    },
    {
        id: 25,
        nome: "Delina",
        marca: "Parfums de Marly",
        categoria: "Feminino",
        tipo: "Importado",
        preco: 2300.00,
        descricao: "Delina de Parfums de Marly é um perfume Floral Feminino lançado em 2017 e assinado por Quentin Bisch. As notas de topo são Lichia, Ruibarbo, Bergamota e Noz-moscada; as notas de coração são Rosa Turca, Peônia, Almíscar e Baunilha; as notas de fundo são Cashmeran, Cedro, Incenso e Vetiver.",
        imagem: "assets/perfumes/Delina.webp",
        destaque: true
    },
    {
        id: 26,
        nome: "Durrat Al Aroos",
        marca: "Al Wataniah",
        categoria: "Feminino",
        tipo: "Árabe",
        preco: 290.00,
        descricao: "Durrat Al Aroos de Al Wataniah é um perfume Oriental Floral requintado. As notas de topo são Almíscar Branco e Cipriol; as notas de coração são Açafrão, Cardamomo e Baunilha; as notas de fundo são Guaiacwood e Couro.",
        imagem: "assets/perfumes/Durrat Al Aroos.webp",
        destaque: false
    },
    {
        id: 27,
        nome: "Eclaire",
        marca: "Lattafa Perfumes",
        categoria: "Feminino",
        tipo: "Árabe",
        preco: 390.00,
        descricao: "Eclaire de Lattafa Perfumes é um perfume Gourmand lançado em 2024. As notas de topo são Caramelo, Leite e Açúcar; as notas de coração são Mel e Flores Brancas; as notas de fundo são Baunilha e Pralinê.",
        imagem: "assets/perfumes/Eclaire.webp",
        destaque: true
    },
    {
        id: 28,
        nome: "Eclaire-Banoffe",
        marca: "Lattafa Perfumes",
        categoria: "Compartilhável",
        tipo: "Árabe",
        preco: 410.00,
        descricao: "Eclaire Banoffee de Lattafa é um perfume gourmand lançado como variação do Eclaire. Apresenta notas de topo de Banana e Caramelo Doce; notas de coração de Biscoito, Leite e Manteiga; e notas de fundo de Baunilha e Cacau.",
        imagem: "assets/perfumes/Eclaire-Banoffe.webp",
        destaque: false
    },
    {
        id: 29,
        nome: "Eclaire-Pistache",
        marca: "Lattafa Perfumes",
        categoria: "Compartilhável",
        tipo: "Árabe",
        preco: 410.00,
        descricao: "Eclaire Pistache de Lattafa é um perfume gourmand cremoso e rico. As notas de topo são Pistache Tostado e Creme de Amêndoa; as notas de coração são Lactonas, Caramelo e Flor de Laranjeira; as notas de fundo são Baunilha, Fava Tonka e Pralinê.",
        imagem: "assets/perfumes/Eclaire-Pistache.webp",
        destaque: false
    },
    {
        id: 30,
        nome: "Fakhar Black",
        marca: "Lattafa Perfumes",
        categoria: "Masculino",
        tipo: "Árabe",
        preco: 310.00,
        descricao: "Fakhar Black de Lattafa Perfumes é um perfume Âmbar Fragrante lançado em 2021. As notas de topo são Maçã, Gengibre e Bergamota; as notas de coração são Sálvia, Bagas de Zimbro e Gerânio; as notas de fundo são Amberwood, Fava Tonka, Cedro e Vetiver.",
        imagem: "assets/perfumes/Fakhar Black.webp",
        destaque: false
    },
    {
        id: 31,
        nome: "Fakhar Gold",
        marca: "Lattafa Perfumes",
        categoria: "Masculino",
        tipo: "Árabe",
        preco: 340.00,
        descricao: "Fakhar Gold (Extrait) de Lattafa Perfumes é um perfume Amadeirado Especiado lançado em 2023. As notas de topo são Toranja, Vetiver e Pimenta Rosa; as notas de coração são Tuberosas e Cardamomo; as notas de fundo são Âmbar, Cashmeran e Couro.",
        imagem: "assets/perfumes/Fakhar Gold.webp",
        destaque: false
    },
    {
        id: 32,
        nome: "Fakhar Platin",
        marca: "Lattafa Perfumes",
        categoria: "Masculino",
        tipo: "Árabe",
        preco: 320.00,
        descricao: "Fakhar Lattafa Platin / Silver é um perfume aromático e marcante. Apresenta notas de topo de Pimenta, Bergamota e Cítricos; notas de coração de Lavanda, Cardamomo e Patchouli; e notas de fundo de Âmbar, Olibano e Sândalo.",
        imagem: "assets/perfumes/Fakhar Platin.webp",
        destaque: false
    },
    {
        id: 33,
        nome: "Fakhar Rose",
        marca: "Lattafa Perfumes",
        categoria: "Feminino",
        tipo: "Árabe",
        preco: 310.00,
        descricao: "Fakhar Rose de Lattafa Perfumes é um perfume Floral Frutado lançado em 2021. As notas de topo são Frutas do Bosque, Romã, Lírio e Aldeídos; as notas de coração são Tuberosa, Jasmim, Gardenia, Ylang-Ylang e Rosa; as notas de fundo são Baunilha, Ambrosan, Sândalo e Almíscar.",
        imagem: "assets/perfumes/Fakhar Rose.webp",
        destaque: false
    },
    {
        id: 34,
        nome: "Hayaati Blue",
        marca: "Lattafa Perfumes",
        categoria: "Masculino",
        tipo: "Árabe",
        preco: 260.00,
        descricao: "Hayaati de Lattafa Perfumes (conhecido pelo frasco azul/preto) é um perfume Amadeirado Aromático lançado em 2020. As notas de topo são Maçã e Bergamota; as notas de coração são Canela e Madeira de Bétula; as notas de fundo são Almíscar e Âmbar.",
        imagem: "assets/perfumes/Hayaati Blue.webp",
        destaque: false
    },
    {
        id: 35,
        nome: "Hayaati Rosa",
        marca: "Lattafa Perfumes",
        categoria: "Feminino",
        tipo: "Árabe",
        preco: 260.00,
        descricao: "Hayaati Florence (Hayaati Rosa) de Lattafa Perfumes é um perfume Floral Frutado Gourmand. As notas de topo são Toranja, Toranja Rosa e Mandarina; as notas de coração são Pêssego, Flor de Laranjeira e Rosa; as notas de fundo são Baunilha, Almíscar e Pralinê.",
        imagem: "assets/perfumes/Hayaati Rosa.webp",
        destaque: false
    },
    {
        id: 36,
        nome: "Her Confession",
        marca: "Lattafa Perfumes",
        categoria: "Feminino",
        tipo: "Árabe",
        preco: 360.00,
        descricao: "Her Confession de Lattafa Perfumes é uma fragrância floral oriental intensa lançada em 2024. As notas de topo são Mística, Pimenta Rosa e Canela; as notas de coração são Tuberosa, Mahonial e Incenso; as notas de fundo são Baunilha, Fava Tonka e Âmbar.",
        imagem: "assets/perfumes/Her Confession.webp",
        destaque: false
    },
    {
        id: 37,
        nome: "His Confession",
        marca: "Lattafa Perfumes",
        categoria: "Masculino",
        tipo: "Árabe",
        preco: 360.00,
        descricao: "His Confession de Lattafa Perfumes é um perfume amadeirado especiado lançado em 2024. As notas de topo são Cardamomo, Lavanda e Tangerina; as notas de coração são Íris, Benjoin e Patchouli; as notas de fundo são Baunilha, Âmbar e Cedro.",
        imagem: "assets/perfumes/His Confession.webp",
        destaque: false
    },
    {
        id: 38,
        nome: "Indomable",
        marca: "Morph",
        categoria: "Compartilhável",
        tipo: "Importado",
        preco: 1200.00,
        descricao: "Indomable de Morph é um perfume Âmbar Baunilha Compartilhável lançado em 2019. As notas de topo são Açúcar de Caña, Âmbar e Oud; as notas de coração são Cacau, Patchouli e Cravinho; as notas de fundo são Baunilha, Fava Tonka e Sândalo.",
        imagem: "assets/perfumes/Indomable.webp",
        destaque: false
    },
    {
        id: 39,
        nome: "Intrud",
        marca: "Maison Alhambra",
        categoria: "Masculino",
        tipo: "Árabe",
        preco: 250.00,
        descricao: "Intruder (ou Intrud) de Maison Alhambra é uma fragrância amadeirada e picante inspirada em clássicos masculinos. Possui notas de topo de Bergamota e Pimenta Rosa; notas de coração de Lavanda e Cardamomo; e notas de fundo de Vetiver, Âmbar e Patchouli.",
        imagem: "assets/perfumes/Intrud.webp",
        destaque: false
    },
    {
        id: 40,
        nome: "Island-Bliss",
        marca: "Linha Árabe",
        categoria: "Compartilhável",
        tipo: "Árabe",
        preco: 280.00,
        descricao: "Island Bliss (de linhas árabes orientadas a fragrâncias tropicais) é um perfume frutado e aquático. As notas de topo são Coco, Manga e Abacaxi; as notas de coração são Flor de Tiaré e Frangipani; as notas de fundo são Baunilha e Almíscar Branco.",
        imagem: "assets/perfumes/Island-Bliss.webp",
        destaque: false
    },
    {
        id: 41,
        nome: "Island-Breeze",
        marca: "Linha Árabe",
        categoria: "Compartilhável",
        tipo: "Árabe",
        preco: 280.00,
        descricao: "Island Breeze traz nuances cítricas e marinhas tropicais. As notas de topo são Limão Tahitian, Hortelã e Água de Coco; as notas de coração são Notas Marinhas e Sal; as notas de fundo são Madeira Flutuante e Almíscar.",
        imagem: "assets/perfumes/Island-Breeze.webp",
        destaque: false
    },
    {
        id: 42,
        nome: "Khamrah Qahwa",
        marca: "Lattafa Perfumes",
        categoria: "Compartilhável",
        tipo: "Árabe",
        preco: 420.00,
        descricao: "Khamrah Qahwa de Lattafa Perfumes é um perfume Gourmand lançado em 2023. As notas de topo são Canela, Cardamomo e Gengibre; as notas de coração são Café, Frutas Cristalizadas e Pralinê; as notas de fundo são Baunilha, Fava Tonka, Benjoin e Âmbar.",
        imagem: "assets/perfumes/Khamrah Qahwa.webp",
        destaque: false
    },
    {
        id: 43,
        nome: "Khamrah Waha",
        marca: "Lattafa Perfumes",
        categoria: "Compartilhável",
        tipo: "Árabe",
        preco: 410.00,
        descricao: "Khamrah Waha de Lattafa é um desdobramento da linha Khamrah com nuances mais frescas e resinosas. Apresenta notas de topo de Cardamomo e Bergamota; notas de coração de Tâmaras, Prilana e Mirra; e notas de fundo de Baunilha, Âmbar e Oud.",
        imagem: "assets/perfumes/Khamrah Waha.webp",
        destaque: false
    },
    {
        id: 44,
        nome: "King of Arábia",
        marca: "Le Chameau",
        categoria: "Masculino",
        tipo: "Árabe",
        preco: 340.00,
        descricao: "King of Arabia (Le Chameau / Emper) é um perfume amadeirado especiado imponente. As notas de topo são Cardamomo, Bergamota e Artemísia; as notas de coração são Lavanda, Íris e Couro; as notas de fundo são Oud, Amberwood e Baunilha.",
        imagem: "assets/perfumes/King of Arábia.webp",
        destaque: false
    },
    {
        id: 45,
        nome: "La Rive Cuté",
        marca: "La Rive",
        categoria: "Feminino",
        tipo: "Importado",
        preco: 180.00,
        descricao: "Cuté de La Rive é um perfume Floral Frutado lançado em 2013. As notas de topo são Yuzu, Malva e Cassis; as notas de coração são Rosa, Íris, Lírio-do-Vale e Lichia; as notas de fundo são Sândalo, Cedro e Almíscar.",
        imagem: "assets/perfumes/La Rive Cuté.webp",
        destaque: false
    },
    {
        id: 46,
        nome: "La Vivacité",
        marca: "Maison Alhambra",
        categoria: "Feminino",
        tipo: "Árabe",
        preco: 260.00,
        descricao: "La Vivacité de Maison Alhambra é uma fragrância alegre e efervescente. Possui notas de topo de Framboesa e Tangerina; notas de coração de Flor de Laranjeira e Jasmim; e notas de fundo de Marshmallow, Baunilha e Sândalo.",
        imagem: "assets/perfumes/La Vivacité.webp",
        destaque: false
    },
    {
        id: 47,
        nome: "Lattafa Dalal",
        marca: "Lattafa Perfumes",
        categoria: "Compartilhável",
        tipo: "Árabe",
        preco: 240.00,
        descricao: "Dalal de Lattafa Perfumes é um perfume Âmbar Baunilha Compartilhável. As notas de topo são Caramelo e Laranja; as notas de coração são Frutas Secas e Ylang-Ylang; as notas de fundo são Baunilha, Sândalo e Âmbar.",
        imagem: "assets/perfumes/Lattafa Dalal.webp",
        destaque: false
    },
    {
        id: 48,
        nome: "Lattafa Musamam White",
        marca: "Lattafa Perfumes",
        categoria: "Compartilhável",
        tipo: "Árabe",
        preco: 390.00,
        descricao: "Musamam White Intense de Lattafa Perfumes é um perfume Amadeirado Especiado lançado em 2023. As notas de topo são Bergamota, Laranja e Especiarias; as notas de coração são Coco, Ylang-Ylang, Mahonial e Ambrosan; as notas de fundo são Sândalo, Benzoin e Musgo.",
        imagem: "assets/perfumes/Lattafa Musamam White.webp",
        destaque: false
    },
    {
        id: 49,
        nome: "Liquid Brun",
        marca: "Fragrance World",
        categoria: "Masculino",
        tipo: "Árabe",
        preco: 460.00,
        descricao: "Liquid Brun de Fragrance World é um perfume gourmand amadeirado quente lançado em 2024. As notas de topo são Canela, Cardamomo, Açafrão e Bergamota; as notas de coração são Bourbon Vanilla e Flor de Laranjeira; as notas de fundo são Âmbar, Pralinê, Musgo e Madeira de Guaiaco.",
        imagem: "assets/perfumes/Liquid Brun.webp",
        destaque: true
    },
    {
        id: 50,
        nome: "Maahir Black",
        marca: "Lattafa Perfumes",
        categoria: "Masculino",
        tipo: "Árabe",
        preco: 390.00,
        descricao: "Maahir Black Edition de Lattafa Perfumes é um perfume Âmbar Amadeirado lançado in 2019. As notas de topo são Pimenta Preta, Pimenta Rosa e Violeta; as notas de coração são Óleo de Cipriol, Labdanum, Incenso e Gurjan Balsam; as notas de fundo são Couro, Oud, Patchouli, Cedro e Moss.",
        imagem: "assets/perfumes/Maahir Black.webp",
        destaque: false
    },
    {
        id: 51,
        nome: "Maahir Honor",
        marca: "Lattafa Perfumes",
        categoria: "Compartilhável",
        tipo: "Árabe",
        preco: 380.00,
        descricao: "Maahir Honor & Glory de Lattafa Perfumes é um perfume Gourmand Frutado lançado em 2023. As notas de topo são Abacaxi Abafado e Creme de Baunilha; as notas de coração são Pimenta Preta, Canela e Benjoin; as notas de fundo são Baunilha, Cashmeran, Âmbar e Moss.",
        imagem: "assets/perfumes/Maahir Honor.webp",
        destaque: false
    },
    {
        id: 52,
        nome: "Maahir Legacy",
        marca: "Lattafa Perfumes",
        categoria: "Masculino",
        tipo: "Árabe",
        preco: 380.00,
        descricao: "Maahir Legacy de Lattafa Perfumes é um perfume Citrus Aromático lançado em 2023. As notas de topo são Hortelã, Toranja, Limão, Abacaxi e Pimenta Rosa; as notas de coração são Zimbro, Lavanda, Gerânio, Pimenta e Frankincense; as notas de fundo são Ambrosan, Vetiver, Tonka, Baunilha e Cedro.",
        imagem: "assets/perfumes/Maahir Legacy.webp",
        destaque: false
    },
    {
        id: 53,
        nome: "Maison Alhambra Victorioso Myth",
        marca: "Maison Alhambra",
        categoria: "Masculino",
        tipo: "Árabe",
        preco: 260.00,
        descricao: "Victorioso Myth de Maison Alhambra é um perfume aquático aromático inspirado no Invictus Victory Elixir. Apresenta notas de topo de Cardamomo e Pimenta Preta; notas de coração de Lavanda e Incenso; e notas de fundo de Baunilha e Fava Tonka.",
        imagem: "assets/perfumes/Maison Alhambra Victorioso Myth.webp",
        destaque: false
    },
    {
        id: 54,
        nome: "Maison Alhambra Victorioso",
        marca: "Maison Alhambra",
        categoria: "Masculino",
        tipo: "Árabe",
        preco: 240.00,
        descricao: "Victorioso de Maison Alhambra é um perfume Amadeirado Aquático. As notas de topo são Notas Marinhas, Toranja e Tangerina; as notas de coração são Folha de Louro e Jasmim; as notas de fundo são Ambergris, Guaiac Wood, Musgo de Carvalho e Patchouli.",
        imagem: "assets/perfumes/Maison Alhambra Victorioso.webp",
        destaque: false
    },
    {
        id: 55,
        nome: "Musamam Black",
        marca: "Lattafa Perfumes",
        categoria: "Compartilhável",
        tipo: "Árabe",
        preco: 370.00,
        descricao: "Musamam de Lattafa Perfumes (edição tradicional frasco preto com cobra) é um perfume Amadeirado Especiado lançado em 2022. As notas de topo são Açafrão, Tangerina Italiana e Lavanda; as notas de coração são Amberwood, Virginia Cedar e Gerânio; as notas de fundo são Akigalawood, Incenso e Couro.",
        imagem: "assets/perfumes/Musamam Black.webp",
        destaque: false
    },
    {
        id: 56,
        nome: "Nasmaat",
        marca: "Lattafa / My Perfumes",
        categoria: "Compartilhável",
        tipo: "Árabe",
        preco: 270.00,
        descricao: "Nasmaat de Lattafa / My Perfumes é uma fragrância oriental fresca e revitalizante. As notas de topo são Notas Cítricas e Bergamota; as notas de coração são Frutas Tropicais e Flores Brancas; as notas de fundo são Almíscar, Âmbar e Baunilha.",
        imagem: "assets/perfumes/Nasmaat.webp",
        destaque: false
    },
    {
        id: 57,
        nome: "Odyssey Candee",
        marca: "Armaf",
        categoria: "Feminino",
        tipo: "Árabe",
        preco: 290.00,
        descricao: "Odyssey Candee de Armaf é um perfume floral frutado gourmand doce e vibrante. As notas de topo são Frutas Vermelhas e Tangerina; as notas de coração são Caramelo, Flor de Laranjeira e Jasmim; as notas de fundo são Baunilha, Fava Tonka e Almíscar.",
        imagem: "assets/perfumes/Odyssey Candee.webp",
        destaque: false
    },
    {
        id: 58,
        nome: "Queen of Arábia",
        marca: "Le Chameau",
        categoria: "Feminino",
        tipo: "Árabe",
        preco: 310.00,
        descricao: "Queen of Arabia (Le Chameau / Emper) é um perfume floral oriental luxuoso. As notas de topo são Pêssego e Pimenta Rosa; as notas de coração são Rosa, Tuberosa e Ylang-Ylang; as notas de fundo são Baunilha, Âmbar, Sândalo e Patchouli.",
        imagem: "assets/perfumes/Queen of Arábia.webp",
        destaque: false
    },
    {
        id: 59,
        nome: "Sabah Al Ward Delilah",
        marca: "Al Wataniah",
        categoria: "Feminino",
        tipo: "Árabe",
        preco: 290.00,
        descricao: "Sabah Al Ward Delilah de Al Wataniah é uma fragrância floral sofisticada. As notas de topo são Lichia, Ruibarbo e Bergamota; as notas de coração são Rosa Turca e Peônia; as notas de fundo são Baunilha, Cashmeran e Almíscar.",
        imagem: "assets/perfumes/Sabah Al Ward Delilah.webp",
        destaque: false
    },
    {
        id: 60,
        nome: "Sabah Al Ward Garden of Eden",
        marca: "Al Wataniah",
        categoria: "Feminino",
        tipo: "Árabe",
        preco: 290.00,
        descricao: "Sabah Al Ward Garden of Eden de Al Wataniah é um perfume floral verde fresco. As notas de topo são Notas Verdes e Toranja; as notas de coração são Lírio-do-Vale, Jasmim e Rosa; as notas de fundo são Almíscar Branco e Cedro.",
        imagem: "assets/perfumes/Sabah Al Ward Garden of Eden.webp",
        destaque: false
    },
    {
        id: 61,
        nome: "Sabah Al Ward Sugar",
        marca: "Al Wataniah",
        categoria: "Feminino",
        tipo: "Árabe",
        preco: 310.00,
        descricao: "Sabah Al Ward Sugar de Al Wataniah é um perfume gourmand doce. As notas de topo são Açúcar Queimado e Marshmallow; as notas de coração são Baunilha e Flor de Laranjeira; as notas de fundo são Fava Tonka e Almíscar.",
        imagem: "assets/perfumes/Sabah Al Ward Sugar.webp",
        destaque: false
    },
    {
        id: 62,
        nome: "Sabah Al Ward Valentine",
        marca: "Al Wataniah",
        categoria: "Feminino",
        tipo: "Árabe",
        preco: 320.00,
        descricao: "Sabah Al Ward Valentine de Al Wataniah é uma fragrância romântica e apaixonante. As notas de topo são Morango e Pimenta Rosa; as notas de coração são Rosa Vermelha e Orquídea; as notas de fundo são Baunilha e Âmbar.",
        imagem: "assets/perfumes/Sabah Al Ward Valentine.webp",
        destaque: false
    },
    {
        id: 63,
        nome: "Sabah Al Ward",
        marca: "Al Wataniah",
        categoria: "Feminino",
        tipo: "Árabe",
        preco: 280.00,
        descricao: "Sabah Al Ward de Al Wataniah é um perfume Oriental Floral lançado em 2020. As notas de topo são Pimenta Rosa e Tangerina; as notas de coração são Cacaueiro, Flor de Laranjeira e Jasmim Sambac; as notas de fundo são Baunilha, Fava Tonka e Benjoin.",
        imagem: "assets/perfumes/Sabah Al Ward.webp",
        destaque: false
    },
    {
        id: 64,
        nome: "Salvo Intense",
        marca: "Maison Alhambra",
        categoria: "Masculino",
        tipo: "Árabe",
        preco: 250.00,
        descricao: "Salvo Intense de Maison Alhambra é um perfume Âmbar Fougère inspirado no Sauvage EDP. As notas de topo são Bergamota da Calábria e Pimenta; as notas de coração são Lavanda, Pimenta de Szechuan, Pimenta Rosa e Vetiver; as notas de fundo são Ambroxan, Cedro e Labdanum.",
        imagem: "assets/perfumes/Salvo Intense.webp",
        destaque: false
    },
    {
        id: 65,
        nome: "Shagaf Al Ward",
        marca: "Al Wataniah",
        categoria: "Feminino",
        tipo: "Árabe",
        preco: 280.00,
        descricao: "Shagaf Al Ward de Al Wataniah é um perfume Floral Oriental. As notas de topo são Jasmine, May Rose e Osmanthus; as notas de coração são Tuberosa Indiana e Narciso; as notas de fundo são Âmbar e Cedro.",
        imagem: "assets/perfumes/Shagaf Al Ward.webp",
        destaque: false
    },
    {
        id: 66,
        nome: "Sultan Al Lail",
        marca: "Al Wataniah",
        categoria: "Masculino",
        tipo: "Árabe",
        preco: 290.00,
        descricao: "Sultan Al Lail de Al Wataniah é um perfume Amadeirado Aromático. As notas de topo são Zimbro, Cítricos, Laranja Sanguínea e Limão Siciliano; as notas de coração são Pimenta Pimenta, Lavanda, Sálvia e Gerânio; as notas de fundo são Vetiver, Cedro e Patchouli.",
        imagem: "assets/perfumes/Sultan Al Lail.webp",
        destaque: false
    },
    {
        id: 67,
        nome: "Taraf",
        marca: "Lattafa Pride",
        categoria: "Compartilhável",
        tipo: "Árabe",
        preco: 360.00,
        descricao: "Taraf de Lattafa Pride é um perfume Amadeirado Oriental rico e elegante. As notas de topo são Açafrão, Bergamota e Hortelã; as notas de coração são Rose, Âmbar e Madeira de Bétula; as notas de fundo são Oud, Couro e Sândalo.",
        imagem: "assets/perfumes/Taraf.webp",
        destaque: false
    },
    {
        id: 68,
        nome: "Tharwar-Gold",
        marca: "Lattafa Pride",
        categoria: "Feminino",
        tipo: "Árabe",
        preco: 340.00,
        descricao: "Tharwah Gold de Lattafa Pride é um perfume Oriental Floral lançado em 2022. As notas de topo são Bergamota e Lavanda; as notas de coração são Flor de Laranjeira e Jasmim Egípcio; as notas de fundo são Baunilha, Âmbar e Vetiver.",
        imagem: "assets/perfumes/Tharwar-Gold.webp",
        destaque: false
    },
    {
        id: 69,
        nome: "Veneno Bianco",
        marca: "Linha Árabe",
        categoria: "Feminino",
        tipo: "Árabe",
        preco: 320.00,
        descricao: "Veneno Bianco (de linhas árabes inspiradas na perfumaria de luxo) é uma fragrância floral branca envolvente. As notas de topo são Néroli e Bergamota; as notas de coração são Tuberosa, Jasmim e Flor de Laranjeira; as notas de fundo são Baunilha, Almíscar e Âmbar.",
        imagem: "assets/perfumes/Veneno Bianco.webp",
        destaque: false
    },
    {
        id: 70,
        nome: "Veneno Black",
        marca: "Linha Árabe",
        categoria: "Masculino",
        tipo: "Árabe",
        preco: 320.00,
        descricao: "Veneno Black é uma fragrância amadeirada, sensual e noturna. As notas de topo são Pimenta Preta e Cardamomo; as notas de coração são Couro, Incenso e Patchouli; as notas de fundo são Oud, Baunilha e Âmbar.",
        imagem: "assets/perfumes/Veneno Black.webp",
        destaque: false
    },
    {
        id: 71,
        nome: "Veneno Scarlat",
        marca: "Linha Árabe",
        categoria: "Feminino",
        tipo: "Árabe",
        preco: 320.00,
        descricao: "Veneno Scarlat traz uma combinação frutada, picante e sedutora. As notas de topo são Frutas Vermelhas e Pimenta Rosa; as notas de coração são Rosa Escura e Açafrão; as notas de fundo são Baunilha, Âmbar e Madeiras Quentes.",
        imagem: "assets/perfumes/Veneno Scarlat.webp",
        destaque: false
    },
    {
        id: 72,
        nome: "Victoria",
        marca: "Maison Alhambra",
        categoria: "Feminino",
        tipo: "Árabe",
        preco: 280.00,
        descricao: "Victoria (Maison Alhambra / Lattafa) é um perfume floral frutado sofisticado. As notas de topo são Frutas Silvestres e Tangerina; as notas de coração são Jasmim, Flor de Laranjeira e Peônia; as notas de fundo são Baunilha, Pralinê e Sândalo.",
        imagem: "assets/perfumes/Victoria.webp",
        destaque: false
    },
    {
        id: 73,
        nome: "Vip Pour Femme",
        marca: "Linha Árabe",
        categoria: "Feminino",
        tipo: "Árabe",
        preco: 270.00,
        descricao: "VIP Pour Femme é um perfume floral frutado sedutor. As notas de topo são Maracujá e Rum; as notas de coração são Almíscar e Gardenia; as notas de fundo são Baunilha e Fava Tonka.",
        imagem: "assets/perfumes/Vip Pour Femme.webp",
        destaque: false
    },
    {
        id: 74,
        nome: "Vulcan Baie",
        marca: "Fragrance World",
        categoria: "Compartilhável",
        tipo: "Árabe",
        preco: 290.00,
        descricao: "Vulcan Baie de Fragrance World (da linha Vulcan) é um perfume frutado e aromático fresco. As notas de topo são Bagas Vermelhas e Cítricos; as notas de coração são Pimenta Rosa e Hortelã; as notas de fundo são Vetiver e Almíscar.",
        imagem: "assets/perfumes/Vulcan Baie.webp",
        destaque: false
    },
    {
        id: 75,
        nome: "Vulcan Feu",
        marca: "Fragrance World",
        categoria: "Masculino",
        tipo: "Árabe",
        preco: 290.00,
        descricao: "Vulcan Feu é uma fragrância quente, especiada e resinosa. As notas de topo são Canela, Pimenta e Laranja Amarga; as notas de coração são Incenso e Amberwood; as notas de fundo são Baunilha, Couro e Sândalo.",
        imagem: "assets/perfumes/Vulcan Feu.webp",
        destaque: false
    },
    {
        id: 76,
        nome: "Vulcan Sable",
        marca: "Fragrance World",
        categoria: "Masculino",
        tipo: "Árabe",
        preco: 290.00,
        descricao: "Vulcan Sable traz nuances amadeiradas e desérticas. As notas de topo são Sálvia e Cardamomo; as notas de coração são Iris e Notas Minerais; as notas de fundo são Cedro, Couro e Âmbar.",
        imagem: "assets/perfumes/Vulcan Sable.webp",
        destaque: false
    },
    {
        id: 77,
        nome: "WATANI INTENSE",
        marca: "Al Wataniah",
        categoria: "Compartilhável",
        tipo: "Árabe",
        preco: 310.00,
        descricao: "Watani Intense de Al Wataniah é um perfume Oriental Amadeirado profundo. As notas de topo são Cravo-da-Índia, Mel e Cítricos; as notas de coração são Baunilha, Sálvia e Rose; as notas de fundo são Oud, Sândalo e Âmbar.",
        imagem: "assets/perfumes/WATANI INTENSE.webp",
        destaque: false
    },
    {
        id: 78,
        nome: "Watani Pink",
        marca: "Al Wataniah",
        categoria: "Feminino",
        tipo: "Árabe",
        preco: 290.00,
        descricao: "Watani Pink de Al Wataniah é uma fragrância floral frutada e doce. As notas de topo são Morango, Frutas Tropicais e Cítricos; as notas de coração são Rosa, Jasmim e Lírio; as notas de fundo são Baunilha, Almíscar e Âmbar.",
        imagem: "assets/perfumes/Watani Pink.webp",
        destaque: false
    },
    {
        id: 79,
        nome: "Watani",
        marca: "Al Wataniah",
        categoria: "Compartilhável",
        tipo: "Árabe",
        preco: 280.00,
        descricao: "Watani de Al Wataniah é um perfume Oriental tradicional refinado. As notas de topo são Tropical Fruits e Herbal Notes; as notas de coração são Floral Notes e Spices; as notas de fundo são Musk, Sweet Notes e Woodsy Notes.",
        imagem: "assets/perfumes/Watani.webp",
        destaque: false
    },
    {
        id: 80,
        nome: "Ya Habibti",
        marca: "Asdaaf",
        categoria: "Feminino",
        tipo: "Árabe",
        preco: 290.00,
        descricao: "Ya Habibti de Lattafa / Asdaaf é uma fragrância romântica e feminina. As notas de topo são Pêssego e Frutas Vermelhas; as notas de coração são Flor de Laranjeira e Rosa; as notas de fundo são Baunilha, Almíscar e Caramelo.",
        imagem: "assets/perfumes/Ya Habibti.webp",
        destaque: false
    },
    {
        id: 81,
        nome: "Yara Candy",
        marca: "Lattafa Perfumes",
        categoria: "Feminino",
        tipo: "Árabe",
        preco: 340.00,
        descricao: "Yara Candy de Lattafa Perfumes é um perfume Gourmand Frutado lançado em 2024. As notas de topo são Groselha Preta e Tangerina Verde; as notas de coração são Morango Doce e Gardenia; as notas de fundo são Baunilha, Amber vanilla e Almíscar.",
        imagem: "assets/perfumes/Yara Candy.webp",
        destaque: false
    },
    {
        id: 82,
        nome: "Yara Elixir",
        marca: "Lattafa Perfumes",
        categoria: "Feminino",
        tipo: "Árabe",
        preco: 360.00,
        descricao: "Yara Elixir de Lattafa Perfumes é a versão mais densa e marcante da linha Yara, lançada em 2024. As notas de topo são Cassis e Pêssego; as notas de coração são Tuberosa e Jasmine Sambac; as notas de fundo são Baunilha Bourbon, Pralinê e Âmbar.",
        imagem: "assets/perfumes/Yara Elixir.webp",
        destaque: false
    },
    {
        id: 83,
        nome: "Yara Moi",
        marca: "Lattafa Perfumes",
        categoria: "Feminino",
        tipo: "Árabe",
        preco: 290.00,
        descricao: "Yara Moi de Lattafa Perfumes (conhecido como Yara Branco) é um perfume Âmbar Gourmand lançado em 2022. As notas de topo são Pêssego e Jasmim; as notas de coração são Caramelo e Âmbar; as notas de fundo são Patchouli e Sândalo.",
        imagem: "assets/perfumes/Yara moi.webp",
        destaque: false
    },
    {
        id: 84,
        nome: "Yara Rosa",
        marca: "Lattafa Perfumes",
        categoria: "Feminino",
        tipo: "Árabe",
        preco: 290.00,
        descricao: "Yara de Lattafa Perfumes (frasco rosa tradicional) é um perfume Âmbar Baunilha lançado em 2020. As notas de topo são Orquídea, Heliotrópio e Tangerina; as notas de coração são Acordo Gourmand e Frutas Tropicais; as notas de fundo são Baunilha, Almíscar e Sândalo.",
        imagem: "assets/perfumes/Yara Rosa.webp",
        destaque: true
    },
    {
        id: 85,
        nome: "Yara Tous",
        marca: "Lattafa Perfumes",
        categoria: "Feminino",
        tipo: "Árabe",
        preco: 310.00,
        descricao: "Yara Tous de Lattafa Perfumes (frasco amarelo) é um perfume Floral Frutado Gourmand lançado em 2023. As notas de topo são Manga, Coco e Maracujá; as notas de coração são Jasmim, Flor de Laranjeira e Heliotrópio; as notas de fundo são Baunilha, Cashmeran e Almíscar.",
        imagem: "assets/perfumes/Yara Tous.webp",
        destaque: false
    },
    {
        id: 86,
        nome: "Yumyum",
        marca: "Linha Árabe",
        categoria: "Feminino",
        tipo: "Árabe",
        preco: 310.00,
        descricao: "Yumyum (de linhas gourmands árabes) é uma fragrância extremamente doce e apetitosa. As notas de topo são Açúcar, Chantilly e Marshmallow; as notas de coração são Baunilha e Lactonas; as notas de fundo são Fava Tonka e Almíscar Branco.",
        imagem: "assets/perfumes/Yumyum.webp",
        destaque: false
    },
    {
        id: 87,
        nome: "Afeef",
        marca: "Lattafa Perfumes",
        categoria: "Feminino",
        tipo: "Árabe",
        preco: 350.00,
        descricao: "Afeef de Lattafa Perfumes é uma nova fragrância lançada em 2024. As notas de topo são Pêssego, Pimenta Rosa e Bergamota; as notas de coração são Tuberosa, Flor de Laranjeira e Jasmim; as notas de fundo são Pralinê, Âmbar, Sândalo e Patchouli.",
        imagem: "assets/perfumes/Afeef.webp",
        destaque: false
    },
    {
        id: 88,
        nome: "ASAD",
        marca: "Lattafa Perfumes",
        categoria: "Masculino",
        tipo: "Árabe",
        preco: 320.00,
        descricao: "Asad de Lattafa Perfumes é um perfume Âmbar Amadeirado Masculino lançado em 2021. As notas de topo são Pimenta Preta, Abacaxi e Tabaco; as notas de coração são Café, Patchouli e Íris; as notas de fundo são Âmbar, Baunilha, Madeira Seca, Benjoin e Labdanum.",
        imagem: "assets/perfumes/ASAD.webp",
        destaque: true
    },
    {
        id: 90,
        nome: "Attar Al Wesal",
        marca: "Al Wataniah",
        categoria: "Masculino",
        tipo: "Árabe",
        preco: 290.00,
        descricao: "Attar Al Wesal de Al Wataniah é um perfume Oriental Amadeirado envolvente e sofisticado. As notas de topo são Pera, Bergamota, Lavanda e Hortelã; as notas de coração são Cardamomo e Canela; as notas de fundo são Casca de Baunilha Negra, Âmbar, Cedro e Patchouli.",
        imagem: "assets/perfumes/Attar Al Wesal.webp",
        destaque: false
    },
    {
        id: 91,
        nome: "KHAMRAH",
        marca: "Lattafa Perfumes",
        categoria: "Compartilhável",
        tipo: "Árabe",
        preco: 380.00,
        descricao: "Khamrah de Lattafa Perfumes é um perfume Aromático Especiado Compartilhável lançado em 2022. As notas de topo são Canela, Noz-moscada e Bergamota; as notas de coração são Tâmaras, Pralinê, Tuberosa e Mahonial; as notas de fundo são Baunilha, Fava Tonka, Benzoin, Mirra, Amberwood e Madeira de Akigala.",
        imagem: "assets/perfumes/KHAMRAH.webp",
        destaque: true
    }
];

// Exportação global para uso sem módulos
window.produtosData = produtos;
